language: ruby

rvm:
- jruby-head

install: bundle install --without development --deployment --jobs=3 --retry=3

cache:
  directories:
  - vendor/bundle

env:
  global:
    - MONGODB=3.0.2

before_script:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz -O /tmp/mongodb.tgz
  - tar -xvf /tmp/mongodb.tgz
  - mkdir /tmp/data
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --dbpath /tmp/data --bind_ip 127.0.0.1 &> /dev/null &

script:
- bundle exec rspec spec