language: ruby
rvm:
- jruby-9.0.0.0.rc1
install: bundle install --without development --deployment --jobs=3 --retry=3
cache:
  directories:
  - vendor/bundle
services:
  - mongodb
script:
- bundle exec rspec spec